version: '3'
services:

  db:
    hostname: postgres
    image: postgres:16
    container_name: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
    
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3
    container_name: rabbitmq
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=mypass
      
  worker:
    build: .
    command: celery -A worker.celery_app worker --loglevel=info
    container_name: worker
    depends_on:
      - rabbitmq
      - db

  web:
    build: .
    command: >
      sh -c "alembic upgrade head
      && python main.py"
    container_name: web
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - worker
      - rabbitmq
      - db